# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: My_Agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $OrganizationName = "debduttachatterjee09"
      $ProjectName = "Test_Pipeline"
      $sendmailto = "debduttachatterjee09@gmail.com,testerdemo1995@gmail.com"
      $mysubject = "Test Mail Subjcet"
      $PAT="wabnqnner2wsrwa3vd3irlgz2gxhiep2ykteaxuupi7s3lgwyuhq"
      $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$PAT"))
      
      $HeaderMail = @{
          Authorization = "Basic $encodedCreds"
      }
      
      #Get the tfsid
      
      $userentitlementurl = "https://vsaex.dev.azure.com/${OrganizationName}/_apis/userentitlements?api-version=7.1-preview.1"
      
      $response = Invoke-RestMethod -Uri $userentitlementurl -Method Get -Headers $HeaderMail
      
      #Filter by sendmailto
      $tfsid = ($response.value| where {$_.user.mailAddress -eq $sendmailto}).id
      
      Write-Host $tfsid
      
      ##send mail
      $urimail = "https://vsrm.dev.azure.com/${OrganizationName}/${ProjectName}/_apis/Release/sendmail/168?api-version=7.1-preview.1"
      $requestBody =
      @"
      {
          "senderType": 1,
          "to": {
              "tfsIds": [
                  "$tfsid"
              ],
              "emailAddresses": []
          },
          "subject": "$mysubject",
          "sections": [
              5,
              0,
              1,
              2,
              4
          ]
      }
      "@
      Try {
      Invoke-RestMethod -Uri $urimail -Body $requestBody -Method POST -ContentType "application/json" -Headers $HeaderMail
      }
      Catch {
      $_.Exception
      }
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
